config/routes.rb
Rails.application.routes.draw do
  
  
  mount Lines::Engine => "/pages"#, as: :blog
  # Lines::Engine.routes.append do
  #   resources :articles, path: '', only: [:index, :show] do
  #     get 'page/:page', action: :index, on: :collection
  #   end
  # end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get  'project', to: 'static_pages#project'
  root 'events#index' 

  resources :blogs, only: [:show, :index], as: :articles, path: "blog" do
    get :to_blog, :on => :member
    get :to_pages, :on => :member
  end
  resources :services, only: [:show, :index]
  resources :events, only: [:show, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/lines/articles/_article.html.erb
<div class="article first">

<% cache article do %>

  <% unless article.image_url.blank? %>
    <div class="hero_image">
      <%= link_to article_path(article) do %>
        <img src="<%= article.image_url %>" alt="<%= article.title %>" />
      <% end %>
    </div>
  <% end %>

  <div class="article_header">
    <h1><%= link_to article.title, article_path(article) %></h1>
    <h2><%= article.sub_title %></h2>
    <div class="author_name"><span>by</span> <%= display_article_authors(article) %></div>
  </div>

  <div class="article_teaser">
    <%= render_teaser(article, article_counter) %>
  </div>

  <div class="article_content">
    <%= markdown article.content %>
    <% if article.document? %>
    <div class="article_document">
      <%= link_to "Download #{article.document.file.filename}", article.document_url %>
    </div>
    <% end %>
  </div>

  <% unless article.gplus_url.blank? %>
    <div class="article_facebook">
      <a href="<%= article.gplus_url %>">Обсудить статью в Facebook</a>
    </div>
  <% end %>
  
  <hr>

  <div class="article_footer">
    Written on <span class="published_at"><%= article.published_at.to_date %></span> by <%= display_article_authors(article, true) %>
  </div>
  
<% end %>
</div>

app/views/lines/articles/_article_collection.html.erb
<%= render partial: 'lines/articles/article_small', locals: { article_small: article_collection, article_class: 'small', article_counter: article_collection_counter } %>

<% if (article_collection_counter % 2) != @offset.to_i %>
  <div class="breaker" style="clear:both;height:1px;line-height:1px">&nbsp;</div>
<% end %>

app/views/lines/articles/_article_small.html.erb
<div class="article <%= article_class %>">
<% cache "#{article_small}_small" do %>
  <% unless article_small.image_url.blank? %>
    <div class="hero_image">
      <%= link_to article_path(article_small) do %>
        <img src="<%= article_small.image_url %>" alt="<%= article_small.title %>" />
      <% end %>
    </div>
  <% end %>

  <div class="article_header">
    <h1><%= link_to article_small.title, article_path(article_small) %></h1>
    <h2><%= article_small.sub_title %></h2>
    <div class="author_name"><span>by</span> <%= display_article_authors(article_small) %></div>
  </div>

  <div class="article_teaser">
    <%= render_teaser(article_small).html_safe %>
    <div class="more-link">
      <%= link_to "Перейти к статье", article_path(article_small) %>
    </div>
  </div>
<% end %>
</div>

app/views/lines/articles/index.html.erb
<div class="rss">
    <%= link_to image_tag("ic_rss.png"), articles_url(format: "atom") %>
</div>

<div id="articles">
  <% if !@first_article.nil? && @first_article.featured? %>
  	<% aclass = "first" %>
  <% else %>
  	<% aclass = "small" %>
  	<% @offset = "1" %>
  <% end %>
  <%= render partial: 'lines/articles/article_small', locals: { article_small: @first_article, article_class: aclass, article_counter: -1 } unless @first_article.nil? %>
  <%= render partial: 'lines/articles/article_collection', collection: @articles, offset: @offset %>
</div>

<% if @articles.total_pages > 1 %>
<hr>
<div id="pagination">
  <%= paginate @articles, outer_window: 1, window: 2, theme: 'lines' %>
</div>
<% end %>

app/views/lines/articles/show.html.erb
<%= render @article, article_counter: -1 %>

<div id="articles">
  <%= render partial: 'lines/articles/article_collection', collection: @related_articles %>
</div>