config/routes.rb
Rails.application.routes.draw do
  
  
  mount Lines::Engine => "/pages"#, as: :blog
  # Lines::Engine.routes.append do
  #   resources :articles, path: '', only: [:index, :show] do
  #     get 'page/:page', action: :index, on: :collection
  #   end
  # end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get  'project', to: 'static_pages#project'
  root 'events#index' 

  resources :blogs, only: [:show, :index], as: :articles, path: "blog" do
    get :to_blog, :on => :member
    get :to_pages, :on => :member
  end
  resources :services, only: [:show, :index]
  resources :events, only: [:show, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/lines/_blog_header.html.erb
<%= render 'layouts/header' %>
<%= render 'layouts/lines/markdown_cheatsheet' %>

<header>
  <% if params[:action] != "index" %>
  <div id="logo">
    <%=link_to_if(params[:controller] != "blogs", "К постам", root_path){ link_to( "К постам", articles_path ) }%>
  </div>
  <% end %>
  <div id="lines">
    <p>Блог о событиях. Заходите после <%= link_to("апрельской", service_path(2), style: "color: red;") %> поездки посмотреть как проходило мероприятие.</p>
  </div>
</header>

app/views/layouts/lines/_pages_header.html.erb
<% if current_lines_user %>
  <%= render_navbar do %>
    <%= link_to t('lines.buttons.new_article').html_safe, new_admin_article_path, class: "btn btn-new-article highlight" %>  
    <%= link_to t('lines.buttons.dashboard').html_safe, admin_articles_path, class: "btn btn-view-blog" %>
  <% end %>
  <div class="spacer"></div>
<% else %>
  <%= render 'layouts/header' %>
<% end %>

<%= render 'layouts/lines/markdown_cheatsheet' %>

<header>
  <% if params[:action] != "index" %>
  <div id="logo">
    <a href=<%= "#{root_path}"%>>
      <% if CONFIG[:logo].empty? %>
        <% CONFIG[:blog_name] %>
        К статьям
      <% else %>
        <img src="<%= CONFIG[:logo] %>" alt="<%= CONFIG[:blog_name] %>" />
      <% end %>
    </a>
  </div>
  <% end %>
  <div id="lines">
    <%= CONFIG[:short_description].html_safe %>
  </div>
</header>

app/views/layouts/lines/application.html.erb
<!doctype html>
<html class="no-js">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta charset="UTF-8" />
  <meta name="author" content="<%= CONFIG[:meta_author] %>" />
  <meta name="revisit-after" content="3 days" />
  <meta name="robots" content="index,follow" />
  <%= display_meta_tags site: CONFIG[:title_short] %>
  <meta name="geo.position" CONTENT="<%= CONFIG[:geo_position] %>">
  <meta name="geo.placename" CONTENT="<%= CONFIG[:geo_address] %>">
  <meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1" />
  
  <%= yield :head %>
  <%= auto_discovery_link_tag(:atom, articles_url(format: "atom"), {title: CONFIG[:feed_title]}) %>
  <%= stylesheet_link_tag    "lines/application", media: "all" %>
  <%= javascript_include_tag "lines/application" %>
  <%= javascript_include_tag('application') %>
  <%= csrf_meta_tags %>
</head>
<body id="top">
<% if params[:controller] == "blogs" %>
  <%= render 'layouts/lines/blog_header' %>
<% else %>
  <%= render 'layouts/lines/pages_header' %>
<% end %>

<div class="container">
  <%= render 'lines/shared/flash' %>
  <%= yield %>
</div>
<%= render 'layouts/contacts' %>
<%= render 'lines/shared/footer' %>

</body>
</html>

app/views/layouts/lines/preview.html.erb
<!doctype html>
<html class="no-js">
<head>
  <meta charset="UTF-8" />
  <%= display_meta_tags site: CONFIG[:title_short] %>
  <meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1" />
  <%= favicon_link_tag %>
  <%= yield :head %>
  <%= stylesheet_link_tag    "lines/application", media: "all" %>
  <%= javascript_include_tag "lines/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield :navbar %>

<%= render 'layouts/lines/markdown_cheatsheet' %>

<header>
  <div id="logo">
    <a href="/">
      <% if CONFIG[:logo].empty? %>
        <%= CONFIG[:blog_name] %>
      <% else %>
        <img src="<%= CONFIG[:logo] %>" alt="<%= CONFIG[:blog_name] %>" />
      <% end %>
    </a>
  </div>
  <div id="lines">
    <%= CONFIG[:short_description].html_safe %>
  </div>
</header>

<div class="container">
  <%= render 'lines/shared/flash' %>
  <%= yield %>
</div>

<%= render 'lines/shared/footer' %>

</body>
</html>