config/routes.rb
Rails.application.routes.draw do
  
  
  mount Lines::Engine => "/pages"#, as: :blog
  # Lines::Engine.routes.append do
  #   resources :articles, path: '', only: [:index, :show] do
  #     get 'page/:page', action: :index, on: :collection
  #   end
  # end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get  'project', to: 'static_pages#project'
  root 'events#index' 

  resources :blogs, only: [:show, :index], as: :articles, path: "blog" do
    get :to_blog, :on => :member
    get :to_pages, :on => :member
  end
  resources :services, only: [:show, :index]
  resources :events, only: [:show, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  has_one :pic,  dependent: :destroy

  validates :name, :description, presence: true
  validate :date_cannot_be_in_the_past

  

  accepts_nested_attributes_for :pic

  def date_cannot_be_in_the_past
    if start.present? && start < Date.today
      errors.add(:start, "can't be in the past")
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  SITE_TITLE = "Healthcamp"
  # GET /events
  # GET /events.json
  def index

    set_meta_tags title: 'Мероприятия',
                  description: "Выездной лагерь: возможность потренироваться, пробежки, растяжка, 
                                миофасциальное расслабление, TRX, даже скакалка. Диетология, 
                                спортивное питание и прочее.",
                  open_graph: { title: 'HealthCamp - Kyiv', 
                                type: 'website',
                                url: root_url,
                                site_name: SITE_TITLE,
                                image: 'http://healthcamp.com.ua/healthcamp.jpg'
                              }
    @events = Event.where('start > ?', DateTime.now)
    fresh_when(@events)
  end

  # GET /events/1
  # GET /events/1.json
  def show
    meta_tags = { title: @event.name,
        type: 'website',
        url: url_for(@event)
      }
    meta_tags[:image] = @event.pic.image.url if @event.pic.present?
    set_meta_tags title: "#{@event.name}",
                  description: "Запланированное мероприятие: #{@event.description}",
                  open_graph: meta_tags
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :start)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.slim
p#notice= notice
div class="test" 
	.each_event-close.icon-close
		dic.stripes

	.each_event-inner
		h2  = event.name
		= image_tag event.pic.image.url if event.pic
		p
		  
		  = event.description
		p
		  strong Начало 
		  = I18n.l( event.start, format: "%e %B в %k:%M",  locale: :ru)
		/ = link_to 'Edit', edit_event_path(event)
		/ | \
		/ = link_to 'Back', events_path
	.each_event-overlay

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :start %>
    <%= f.datetime_select :start %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.slim
p#notice =notice

.each_event

h1 style="text-shadow: rgba(0,0,0,0.5) 1px 1px 2px;" Мероприятия

#event.clearfix
  - @events.each do |event|
    .col-xs-12.col-sm-6.col-md-4.item
      event.event
        figure
          img alt="" src="#{event.pic.image.url if event.pic.present?}"
          figcaption
            a.btn.small data-remote="true" href=event_path(event)  Подробнее 
        .excerpt
          time data-title="#{event.start.strftime("%B")}" datetime="#{event.start.strftime("db:‘%Y-%m-%d %H:%M:%S’")}" 
            strong = I18n.l( event.start, format: "%b",  locale: :ru).to_s.mb_chars.capitalize.to_s[0..-2]
            em = event.start.strftime("%e") 
          h6.heading 
            a data-remote="true" href=event_path(event) = event.name
          p = event.description

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class="each_event-show">
	<h2>
	  <%= @event.name %>
	</h2>
	<%= image_tag @event.pic.image.url if @event.pic %>
	<p>
	  <%= @event.description %>
	</p>

	<p>
	  Начало 
	  <%= I18n.l( @event.start, format: "%e %B в %k:%M",  locale: :ru) %>
	</p>

	<%= link_to 'Назад', root_path %>
</div>

app/views/events/show.js.erb
$(".each_event").html("<%= escape_javascript(render partial: "event", locals: {event: @event}) %>");
$('body').addClass('no-scroll');
$('.each_event').fadeIn('fast');

$(".each_event-overlay, .each_event-close").click(function (e) {

  e.preventDefault();
  $('.each_event').fadeOut('fast');
  $('body').removeClass('no-scroll');
});