config/routes.rb
Rails.application.routes.draw do
  
  
  mount Lines::Engine => "/pages"#, as: :blog
  # Lines::Engine.routes.append do
  #   resources :articles, path: '', only: [:index, :show] do
  #     get 'page/:page', action: :index, on: :collection
  #   end
  # end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get  'project', to: 'static_pages#project'
  root 'events#index' 

  resources :blogs, only: [:show, :index], as: :articles, path: "blog" do
    get :to_blog, :on => :member
    get :to_pages, :on => :member
  end
  resources :services, only: [:show, :index]
  resources :events, only: [:show, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/lines/admin/articles/_form.html.erb
<% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    <a href="#" class="close">x</a>
  </div>
<% end %>

<%= form_for([:admin, @article], id: 'article_form') do |f| %>
  <div class="new-article">
    <div class="hero-upload">
      <%= f.file_field :hero_image %>
      <%= f.hidden_field :remove_hero_image %>
      <div class="btn-change-hero"><%= t('lines.buttons.change') %></div>
      <% if @article.short_hero_image.present? %>
        <img src="<%= @article.short_hero_image %>" alt="" />
      <% elsif @article.hero_image? %>
        <img src="<%= @article.hero_image %>" alt="" />
      <% end %>
      <%= f.hidden_field :hero_image_file %>
      <div class="upload-overlay">
        <div class="upload-overlay-close icon-close"></div>
        <div class="upload-overlay-inner">
          <h2><%= t('lines.buttons.select_hero_image') %></h2>
          <div class="btn-remove-hero<%= " show" if @article.hero_image? || @article.short_hero_image %>"><%= t('lines.buttons.remove_hero_image') %></div>
          <%= f.label :hero_image, t('lines.buttons.upload_image') %>
          <div class="hero-images">
            <% Lines::Article::HERO_IMAGES.each_with_index do |h, i| %>
              <img src="<%= "/heroes/#{h}" %>" alt="" class="<%= 'selected-hero-image' if ('/heroes/' + h) == @article.short_hero_image %>" />
            <% end %>
            <%= f.hidden_field :short_hero_image, class: "short-hero-image-cache" %>
          </div>
        </div>
        <div class="hero-background-overlay"></div>
      </div>
    </div>

    <div class="input-field required">
      <%= f.text_field :title, placeholder: true, class: 'title' %>
    </div>

    <div class="input-field">
      <%= f.text_field :sub_title, placeholder: true %>
    </div>

    <div class="input-field">
      <%= f.text_area :teaser, placeholder: true, rows: 1 %>
    </div>

    <div class="input-field editor required">
      <%= f.text_area :content, placeholder: true, rows: 1, data: {editor: "codemirror"} %>
    </div>

    <div class="input-field">
      <div class="documents">
        <%= f.label :document, "#{@article.document? ? @article.document.file.filename + ' <span></span>' : t('lines.buttons.attach_document').html_safe }".html_safe, class: "attachment-label", title: t('lines.buttons.change_attachment').html_safe -%>
        <% if @article.document? %>
          <span class="icon-delete btn-delete-attachment" title="<%= t('lines.buttons.remove_attachment').html_safe %>"></span>
        <% end %>
        <%= f.file_field :document, class: "article-document-value" %>
        <div class="hidden">
          <%= f.hidden_field :document_cache %>
          <%= f.check_box :remove_document %>
        </div>
      </div>

    </div>

    <h2><%= t('activerecord.models.lines/author', count: 2) %> <span style="color: #c10020;">*</span></h2>

    <div class="input-field checkbox">
      <%= f.collection_check_boxes(:author_ids, Lines::Author.all, :id, :name) %>
    </div>

    <h2><%= t('lines.additional_info').html_safe %></h2>

    <div class="input-field">
      <%= f.autocomplete_field :tag_list, autocomplete_tag_name_admin_articles_path, :"data-delimiter" => ', ', placeholder: "Tags" %>
    </div>

    <div class="input-field">
      <%= f.text_field :gplus_url, placeholder: true %>
    </div>

    <div class="input-field required">
      <%= f.text_field :published_at, value: (@article.published_at || Time.now).strftime("%Y-%m-%d"), 'data-behaviour' => 'datepicker', placeholder: "Published on" %>
    </div>

    <%= render_navbar do %>
      <%= f.submit t('lines.buttons.save_article').html_safe, class: "btn btn-save-publish highlight" %>
      <%= link_to t('lines.buttons.cancel').html_safe, admin_articles_path, class: "btn btn-cancel" %>
    <% end %>        

  </div>
<% end %>

app/views/lines/admin/articles/index.html.erb
<%= render_navbar do %>
  <%= link_to t('lines.buttons.new_article').html_safe, new_admin_article_path, class: "btn btn-new-article highlight" %>  
  <%= link_to t('lines.buttons.visit_blog').html_safe, lines.root_path, class: "btn btn-view-blog" %>
<% end %>

<% if @articles_unpublished.size > 0 %>
  <h2><%= t('lines.unpublished_articles').html_safe %></h2>
  <div class="articles-list">
    <% @articles_unpublished.each do |article| %>
      <div class="article unpublished">
        <div class="title">
          <%= link_to article.title, edit_admin_article_path(article), title: article.title %>
        </div>
        <div class="subtitle">
          <%= link_to article.sub_title, edit_admin_article_path(article), title: article.sub_title %>
        </div>
        <div class="actions">
          <div class="left">
            <%= link_to t('lines.buttons.publish').html_safe, admin_article_toggle_publish_path(article), method: :post, class: "btn-publish" %>
            <%=link_to_if(article.oftype == 'pages', "Make a blog post".html_safe, main_app.blog_admin_lines_article_path(article), method: :get, class: "btn-blog"){ 
              link_to( "Make an article".html_safe, main_app.pages_admin_lines_article_path(article), method: :get, class: "btn-pages" ) 
            }%>
          </div>
          <div class="right">
            <%= link_to t('lines.buttons.preview').html_safe, admin_article_path(article) %>
            <%= link_to "", {controller: :articles, action: 'destroy', id: article.id}, data: { confirm: t('lines.confirm').html_safe }, class: "btn-delete icon-delete", method: :delete %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<% if @articles_published.size > 0 %>
  <h2><%= t('lines.published_articles').html_safe %></h2>
  <div class="articles-list">
    <% @articles_published.each do |article| %>
      <div class="article published">
        <div class="title">
          <%= link_to article.title, edit_admin_article_path(article), title: article.title %>
        </div>
        <div class="subtitle">
          <%= link_to article.sub_title, edit_admin_article_path(article), title: article.sub_title %>
        </div>
        <div class="actions">
          <div class="left">
            <% feature_class = article.featured ? 'btn-unfeature icon-unkeep' : 'btn-feature icon-keep' %>
            <%= link_to "", admin_article_toggle_feature_path(article), method: :post, class: "#{feature_class}" %>
            <%= link_to t('lines.buttons.unpublish').html_safe, admin_article_toggle_publish_path(article), method: :post, class: "btn-unpublish" %>
            <%=link_to_if(article.oftype == 'pages', "Make a blog post".html_safe, main_app.blog_admin_lines_article_path(article), method: :get, class: "btn-blog"){ 
              link_to( "Make an article".html_safe, main_app.pages_admin_lines_article_path(article), method: :get, class: "btn-pages" ) 
            }%>
            
          </div>
          <div class="right">
            <%= link_to t('lines.buttons.preview').html_safe, admin_article_path(article) %>
            <%= link_to "", {controller: :articles, action: 'destroy', id: article.id}, data: { confirm: t('lines.confirm').html_safe }, class: "btn-delete icon-delete", method: :delete %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<% if @articles_unpublished.size == 0 && @articles_published.size == 0 %>
  <h2>There are no articles yet</h2>
<% else %>
  <div id="pagination">
    <%= paginate @articles, outer_window: 1, window: 2, theme: 'lines' %>
  </div>
<% end %>